title: Merchandising for Power Blog
baseURL: /
params:
  layout_style: grid
  palette: black
  header:
    title: Merchandising for Power
    logo_img: ""
    has_nav: true
  footer:
    content: "&copy; All rights reserved."
    links: []
    has_social: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
